WITH INFO AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
, RENTAL AS (
    SELECT CAR_ID, START_DATE, END_DATE
           , CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN '대여중'
             ELSE '대여 가능' END AS AVAILABILITY
    FROM INFO
)

SELECT DISTINCT CAR_ID, MAX(AVAILABILITY) -- 같은 ID 중 최신 정보로 
FROM RENTAL
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;