WITH TOTAL AS (
    SELECT A.BOOK_ID, A.CATEGORY, B.SALES_DATE, B.SALES
    FROM BOOK AS A
    LEFT JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
)

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM TOTAL
WHERE SUBSTR(SALES_DATE,1,7) = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY;