WITH TOTAL AS (    
    SELECT A.PRODUCT_CODE, B.PRODUCT_ID, A.PRICE, B.SALES_AMOUNT, B.SALES_DATE
    FROM PRODUCT AS A
    RIGHT JOIN OFFLINE_SALE AS B ON A.PRODUCT_ID = B.PRODUCT_ID 
)
, PRO_MONEY AS (
    SELECT PRODUCT_CODE, PRODUCT_ID, PRICE, SALES_AMOUNT
           , SUM(PRICE*SALES_AMOUNT) AS SALES
    FROM TOTAL 
    GROUP BY PRODUCT_CODE
)
SELECT PRODUCT_CODE, SALES
FROM PRO_MONEY
ORDER BY SALES DESC, PRODUCT_CODE;