WITH TOTAL AS (
    SELECT A.WRITER_ID, A.PRICE, A.STATUS AS PUR_STATUS, B.NICKNAME
    FROM USED_GOODS_BOARD AS A
    LEFT JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
)
, MONEY_TOTAL AS (
    SELECT WRITER_ID AS USER_ID, NICKNAME
           , SUM(PRICE) AS TOTAL_SALES
    FROM TOTAL
    WHERE PUR_STATUS = 'DONE'
    GROUP BY USER_ID
) 

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM MONEY_TOTAL
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;