WITH TOTAL AS (
    SELECT APNT_NO, MCDP_CD, APNT_CNCL_YN, APNT_CNCL_YMD
    FROM APPOINTMENT
    WHERE SUBSTR(APNT_YMD,1,7) = '2022-05'   
)

SELECT MCDP_CD AS 진료과코드, COUNT(APNT_NO) AS 5월예약건수
FROM TOTAL
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC, 진료과코드 ASC;