# WITH TOTAL_ANIMAL AS (
#     SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME, A.DATETIME, B.DATETIME AS OUT_TIME
#            , A.SEX_UPON_INTAKE, B.SEX_UPON_OUTCOME
#     FROM ANIMAL_INS AS A
#     LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
# )
# , ANIMAL_SEX AS (
#     SELECT * 
#     FROM TOTAL_ANIMAL
#     WHERE (SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME LIKE 'Neutered%')
#     OR SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME LIKE 'Spayed%'
# )

# SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
# FROM ANIMAL_SEX
# ORDER BY ANIMAL_ID;

WITH TOTAL_ANIMAL AS (
    SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME, A.DATETIME, B.DATETIME AS OUT_TIME
           , A.SEX_UPON_INTAKE, B.SEX_UPON_OUTCOME
    FROM ANIMAL_INS AS A
    LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
)
, ANIMAL_SEX AS (
    SELECT * 
    FROM TOTAL_ANIMAL
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
    AND SEX_UPON_OUTCOME NOT LIKE 'Intact%'
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_SEX
ORDER BY ANIMAL_ID;