WITH TOTAL_ANIMAL AS (
    SELECT B.ANIMAL_ID,	B.DATETIME, A.INTAKE_CONDITION, B.NAME
    FROM ANIMAL_INS AS A
    RIGHT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID 
)
, INTAKE_NULL AS (
    SELECT ANIMAL_ID, DATETIME,	INTAKE_CONDITION, NAME
    FROM TOTAL_ANIMAL
    WHERE INTAKE_CONDITION IS NULL
)

SELECT ANIMAL_ID, NAME
FROM INTAKE_NULL;