# WITH INFO AS (
# SELECT COUNT(USER_ID) AS PUCHASED_USERS
# FROM USER_INFO
# WHERE YEAR(JOINED) = '2021'
# ) 


# SELECT YEAR(B.SALES_DATE) AS YEAR, 
#        MONTH(B.SALES_DATE) AS MONTH, 
#        COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS , 
#        ROUND(COUNT(DISTINCT B.USER_ID) / INFO.PUCHASED_USERS ,1) AS PUCHASED_RATIO
# FROM INFO, 
# USER_INFO AS A RIGHT JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
# WHERE YEAR(A.JOINED) = '2021'
# GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
# ORDER BY YEAR, MONTH


SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS,
          ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),1) AS PUCHASED_RATIO
FROM USER_INFO AS A 
RIGHT JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH;