# WITH TOTAL_INFO AS (
#     SELECT B.USER_ID, A.JOINED, B.SALES_AMOUNT, B.SALES_DATE
#     FROM USER_INFO AS A
#     RIGHT JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
#     WHERE YEAR(JOINED) = '2021'
# ) -- 전체 고객 111명 
# , CST AS (
#     SELECT USER_ID, SALES_AMOUNT, SALES_DATE
#            , YEAR(SALES_DATE) AS YEAR
#            , MONTH(SALES_DATE) AS MONTH
#     FROM TOTAL_INFO
#     WHERE SALES_AMOUNT > 0
# ) -- 21년 가입 회원 중 상품 구매 111명

# SELECT YEAR, MONTH -- COUNT(USER_ID)
#        , COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
#        , ROUND(((COUNT(USER_ID) / (SELECT COUNT(USER_ID) FROM TOTAL_INFO))),1) AS PUCHASED_RATIO
# FROM CST
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH;


WITH INFO AS (
SELECT COUNT(USER_ID) AS PUCHASED_USERS
FROM USER_INFO
WHERE JOINED LIKE '2021%'
) 

SELECT YEAR(OS.SALES_DATE) AS YEAR , MONTH(OS.SALES_DATE) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS , ROUND(COUNT(DISTINCT OS.USER_ID) / INFO.PUCHASED_USERS ,1) AS PUCHASED_RATIO
FROM INFO, USER_INFO UI RIGHT JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE UI.JOINED LIKE '2021%'
GROUP BY MONTH(OS.SALES_DATE)
ORDER BY YEAR, MONTH
