WITH TOTAL AS (
    SELECT A.ANIMAL_ID, A.NAME, A.DATETIME, B.DATETIME AS OUTS_TIME
    FROM ANIMAL_INS AS A
    LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
) 
,DATE_NULL AS (
    SELECT ANIMAL_ID, NAME, DATETIME, OUTS_TIME
    FROM TOTAL
    WHERE OUTS_TIME IS NULL 
)
,INS_RANK AS (
    SELECT ANIMAL_ID, NAME, DATETIME
           , ROW_NUMBER() OVER(ORDER BY DATETIME) AS ANIMAL_RANK 
    FROM DATE_NULL
)

    SELECT NAME, DATETIME
    FROM INS_RANK
    WHERE ANIMAL_RANK <= 3;