WITH INFO AS (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
)
, MONEY AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM INFO
    GROUP BY FLAVOR
)
, ICE_RANK AS (
    SELECT FLAVOR, TOTAL_ORDER
           , ROW_NUMBER() OVER(ORDER BY TOTAL_ORDER DESC) AS TOTAL_RANK
    FROM MONEY
)

SELECT FLAVOR
FROM ICE_RANK
WHERE TOTAL_RANK <= 3;