WITH AUTHOR AS (
    SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, B.AUTHOR_NAME, A.PUBLISHED_DATE
    FROM BOOK AS A
    LEFT JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
    WHERE CATEGORY = '경제'
)

SELECT BOOK_ID,	AUTHOR_NAME
       ,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR
ORDER BY PUBLISHED_DATE;