WITH INFO AS (
    SELECT A.ANIMAL_ID, A.DATETIME, B.DATETIME AS OUTS_DATETIME, A.NAME
    FROM ANIMAL_INS AS A
    INNER JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
)
, ANIMAL_DATE AS (
    SELECT *
    FROM INFO
    WHERE DATETIME > OUTS_DATETIME
)
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_DATE
ORDER BY DATETIME;