WITH TOTAL AS (
    SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, B.AUTHOR_NAME
           , A.PRICE, A.PUBLISHED_DATE, C.SALES_DATE, C.SALES
    FROM BOOK AS A
    LEFT JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
    LEFT JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
    WHERE SUBSTR(SALES_DATE,1,7) = '2022-01'
)
, SALES AS (
    SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY
           , SUM(PRICE*SALES) AS TOTAL_SALES
    FROM TOTAL 
    GROUP BY AUTHOR_NAME, CATEGORY
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM SALES
ORDER BY AUTHOR_ID, CATEGORY DESC;